### ISSUE TITLE
请教angular2开发移动页面

### ISSUE THREAD

**Issue by lubaohui** [angular-bbs/q-and-a#11]
请教angular2开发移动页面，在form表单输入数据后，需要打开新的页面选择其他数据，并返回form中，希望保留form中的数据；请教下怎么实现，是用路由参数来回传呢，还是直接弹出一个页面选择数据，请帮忙看看，非常感谢！

**Comment by asnowwolf** [comment]
通常不要打开新页面，直接弹出一个modal窗口就行了，这样的话，一切环境都仍然保留原样，不需要重新来。

**Comment by lubaohui** [comment]
谢谢，开始学不熟悉，非常感谢你的帮助。
在2017年01月11日 09:28，雪狼 写道:

通常不要打开新页面，直接弹出一个modal窗口就行了，这样的话，一切环境都仍然保留原样，不需要重新来。
